

trigger:
  branches:
    include:
      - mychanges

resources:
  repositories:
    - repository: 
      name: three-tier-architecture-demo
      type: github
      endpoint: krishmint-git

variables:
  tag: '$(Build.BuildId)'
  containerRegistry: 'dockerhub'

pool:
  name:"" 

stages:
- stage: Build
  displayName: Build image with docker compose
  jobs:
  - job: Build
    displayName: Build
    steps:
    
    - script: |
        sudo apt update
        sudo apt install dos2unix -y
        dos2unix AKS/helm/updatek8smanifest.sh

    - task: ShellScript@2
      inputs:
        scriptPath: "AKS/helm/updatek8smanifest.sh" 
        args: '$(tag)'   

    - task: DockerCompose@1
      displayName: Build docker image
      inputs:
        containerregistrytype: Container Registry
        dockerRegistryEndpoint: $(containerRegistry)
        dockerComposeFile: '**/docker-compose.yaml'
        action: 'Build services'

- stage: push
  displayName: Build image with docker compose
  jobs:
  - job: push
    displayName: push
    steps:
    - task: DockerCompose@1
      displayName: 'Push Docker images'
      inputs:
        containerregistrytype: Container Registry
        dockerRegistryEndpoint: $(containerRegistry)
        dockerComposeFile: '**/docker-compose.yaml'
        action: 'Push services'
        
        

   
