

trigger:
  branches:
    include:
      - master

resources:
   - repo: self
  
variables:
  tag: '$(Build.BuildId)'
  containerRegistry: 'dockerhub'

pool:
  name: '3-tier' 

stages:
- stage: Build
  displayName: Build image with docker compose
  jobs:
  - job: Build
    displayName: Build
    steps:
    
    - script: |
        sudo apt update
        sudo apt install dos2unix -y
        dos2unix AKS/helm/updatek8smanifest.sh

    - task: ShellScript@2
      inputs:
        scriptPath: "AKS/helm/updatek8smanifest.sh" 
        args: '$(tag)'   

    - task: DockerCompose@1
      displayName: Build docker image
      inputs:
        containerregistrytype: Container Registry
        dockerRegistryEndpoint: $(containerRegistry)
        projectName: threetierarch
        dockerComposeFile: '**/docker-compose.yaml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'build'
        

- stage: push
  displayName: push image with docker compose
  jobs:
  - job: push
    displayName: push
    steps:
    - task: DockerCompose@1
      displayName: 'Push Docker images'
      inputs:
        containerregistrytype: Container Registry
        dockerRegistryEndpoint: $(containerRegistry)
        projectName: threetierarch
        dockerComposeFile: '**/docker-compose.yaml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'push'
        
        

   
